nginx:
    image: eva/nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - ~/opt:/opt
      - /Users/joker/opt/htdocs/Dockerfiles/nginx/sites-enabled:/etc/nginx/conf.d/


php:
    image: eva1/php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "memcache"
      - "redis"
    volumes:
      - ~/opt:/opt

mysql:
    image: eva/mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

memcache:
    image: memcached:1.4
    ports:
      - "11211:11211"

redis:
    image: redis:3.0
    ports:
      - "6379:6379"

